### ISSUE TITLE
Why is this repo called simulation-orogen-mars

### ISSUE THREAD

**Issue by jakobs** [rock-simulation/simulation-orogen-mars#16]
and not orogen-mars?

**Comment by goldhoorn** [comment]
The 'rock' standart (lt. Sylvain) should be:

<package>-(orogen-)-name

The other packages here don't follow this principle because the mars user don't want to annoy their users with too much renames. (the packages was created before this knowledge get spread).

P.S.
i personally don't like this naming sceme too

**Comment by jakobs** [comment]
ok, thanks.
